### ISSUE TITLE
Add a method of pausing startup of the application when running inside docker

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1736]
Running in docker can be tricky especially as part of docker-compose actions, and waiting for database services to come up. There are scripts that check that ports in the DB server are answering before starting the API service, but these are unreliable as often DBs answer on these ports before the databases have been created. 

As a simple (if crude) method of solving this problem, it would be helpful to be able to provide an additional command parameter do the Docker image that defines the number of seconds to sleep before running any of the current commands. I would suggest an an optional integer as a second parameter to the Docker `COMMAND`. E.g. the docker compose would look like:

```yaml
    api:
        build:
            context: .
            dockerfile: Dockerfile
        command: migrate 60
```

Which would cause the api service to pause for 60 seconds before running `migrate`
