### ISSUE TITLE
After upgrade from v2.66.2 to 2.104.0 some POST calls fail when REPLICA_DATABASE_URLS is set

### ISSUE THREAD

**Issue by gamer22026** [SolidStateGroup/bullet-train-api#3681]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [X] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

We use Aurora RDS/Postgres with one writer and one reader. We've been using REPLICA_DATABASE_URLS to split reads/writes between these 2 instances. After upgrading from v2.66.2 to v2.104.0, we've seen failing POSTS (both directly through the api and also the UI) that throw a 500 error.  Things like creating feature, create segment override. When we don't set REPLICA_DATABASE_URLS, these all work just fine. Seems like some of the POSTS are not routing to the write instance.

### Steps To Reproduce

Set REPLICA_DATABASE_URLS
Create environment
Try to create feature fails with 500 error

### Expected behavior

Set REPLICA_DATABASE_URLS
Create environment
Try to create feature succeeds

**Comment by gamer22026** [comment]
When the error happens the api server logs:
```
{
  "levelname": "ERROR",
  "message": "Internal Server Error: /api/v1/projects/3/features/",
  "timestamp": "2024-03-26 17:21:06",
  "logger_name": "django.request",
  "process_id": 9,
  "thread_name": "ThreadPoolExecutor-0_0"
}
```
There are no tracebacks in the logs corresponding to the times these internal server errors occur

**Comment by gamer22026** [comment]
Was able to recreate this on v2.104.0  using a brand new blank DB (Aurora RDS/Postgres15) running 1 writer and 1 reader. Initially did not add REPLICA_DATABASE_URLS and was able to create a feature. Then added REPLICA_DATABASE_URLS and again received the Internal Server Error (and no tracebacks recorded). So appears to unrelated to any DB migrations from older flagsmith versions

**Comment by gamer22026** [comment]
The env vars I'm setting in the flagsmith-api
```
       env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: flagsmith
        - name: REPLICA_DATABASE_URLS
          valueFrom:
            secretKeyRef:
              key: REPLICA_DATABASE_URLS
              name: flagsmith
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: DJANGO_SECRET_KEY
              name: flagsmith
        - name: INFLUXDB_URL
          value: http://flagsmith-influxdb2.flagsmith.svc.cluster.local:80
        - name: INFLUXDB_BUCKET
          value: default
        - name: INFLUXDB_ORG
          value: influxdata
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              key: admin-token
              name: flagsmith-influxdb2-auth
        - name: DJANGO_ALLOWED_HOSTS
          value: '*'
        - name: ADMIN_EMAIL
          value: admin@example.com
        - name: EMAIL_BACKEND
          value: django.core.mail.backends.smtp.EmailBackend
        - name: EMAIL_HOST
          value: some.email.host
        - name: EMAIL_PORT
          value: "25"
        - name: EMAIL_USE_TLS
          value: "false"
        - name: ACCESS_LOG_LOCATION
          value: /dev/stdout
        - name: GUNICORN_KEEP_ALIVE
          value: "30"
        - name: ENABLE_ADMIN_ACCESS_USER_PASS
          value: "true"
        - name: ENABLE_TELEMETRY
          value: "false"
        - name: LOG_LEVEL
          value: DEBUG
        - name: SENDER_EMAIL
          value: no-reply@somedomain.com
        - name: TELEMETRY_API_URI
          value: http:/localhost:8000
        - name: LOG_FORMAT
          value: json
```
