### ISSUE TITLE
Github: Research the Github API to determine how we find references to flags in Flagsmith user codebases

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#5066]
Can we add the ability to scan a given repository for usages of Flagsmith flags (see LD's implementation [here](https://docs.launchdarkly.com/home/observability/code-references))?

**Comment by kyle-ssg** [comment]
A note on GH specifically, we should also allow the GitHub search endpoint to include closed PRs / issues, it's very annoying not being able to see those atm.

**Comment by emyller** [comment]
TL;DR: Although the Search API might not be the way forward, GitHub Actions provides the architecture that fits our goal with zero infrastructure costs. We can build a PoC based on CI scripts running on GitHub Actions.

---

During a team conversation on this topic, we thought of using a GitHub integration to create or improve user experience around _cleaning up of stale feature flags_. We want to encourage teams not to keep feature flags in code for long — with few exceptions, e.g. when flags are intrinsic to the control flow of core business rules.

This comment is a product of a research made with the goal of proposing something to build.


## User Experience Proposal

There are a couple good products we could build as a PoC:

1. When viewing stale feature flags in the Flagsmith UI, we can display feature flag references found in repositories from the team's GitHub organization.
2. An email sent regularly to admins with a list of stale flags and references to the code in GitHub.

_Pending feature mockups_.

The above products would contribute to the visibility of stale feature flags in [likely] old code, and is intended to prompt developers to clean them up by making it easier to coordinate work — and maybe positively annoying.


## Code Search API

I've explored a bit of the Search API and it looks very functional, and there might be something we can leverage with it now or in the future. However, given the potential we're idealizing with an integration, I think Search API also brings a lot of guns to a stick fight. It will also require:

- Teams to allow the Flagsmith app to have full read-only access to their code.
- Some discussion around _when_ to trigger API calls, as to avoid GitHub rate limiting and skyrocketing costs.
- Infrastructure to run asynchronous code as a GitHub app — not sure the task processor is the best tool for this, not even for a PoC.
- Mid-term: scaling challenges we'd love to avoid.

Accounting for the fact that most of the above are initial challenges even to a PoC, the Search API might not be the right tool for the goal we want to achieve.


## GitHub Actions

By leveraging GitHub Actions, we can build a CI product that's easy to plug in and comes with a great architecture fit.

- GHA allows for code scans triggered by each team's git-push activity, also expanding visibility to PRs and releases.
- Favoring privacy, **our code** runs in CI runners chosen by each team — could be GitHub runners, or their own. We don't have access to anyone's code.
- It offloads computer work to each team's CI cost with GHA.

![Image](https://github.com/user-attachments/assets/4ba59740-6e3b-49d0-8e51-f053cf8c4199)

The above diagram is an architecture overview of how customers, such as github.com/acmeinc, can plug in a GitHub action from github.com/Flagsmith/ci-tools. A CI workflow snippet in GitHub Actions language would resemble this _untested_ snippet:

```yaml
name: find-flagsmith-code-references

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '0 8 * * *'  # Every day at 8 am UTC

jobs:

  fetch-stale-feature-flags:
    if: github.event_name == 'schedule'
    uses: flagsmith/ci-tools/.github/workflows/fetch-stale-feature-flags.yml@0.0.1
    secrets:
      flagsmith_server_key: ${{ secrets.FLAGSMITH_SERVER_KEY }}
    
  report-code-references-from-stale-feature-flags:
    needs: [fetch-stale-feature-flags]
    if: ${{ needs.fetch-stale-feature-flags.outputs.stale_features }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://ghcr.io/flagsmith/flagsmith-find-code-references:0.0.1
        id: find_stale_flag_code_references
        with:
          features: ${{ needs.fetch-stale-feature-flags.outputs.stale_features }}
          flagsmith_server_key: ${{ secrets.FLAGSMITH_SERVER_KEY }}
      - uses: flagsmith/ci-tools/.github/actions/report-code-references-to-flagsmith.yml@0.0.1
        with:
          references_json: ${{ steps.find_stale_flag_code_references.outputs.references_json }}

  report-code-references-from-diff:
    if: contains(fromJSON('["push", "pull_request"]'), github.event_name)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://ghcr.io/flagsmith/flagsmith-find-code-references:0.0.1
        id: find_diff_flag_code_references
        with:
          from_diff_since: ${{ github.event.pull_request.head.sha }}
          flagsmith_server_key: ${{ secrets.FLAGSMITH_SERVER_KEY }}
      - uses: flagsmith/ci-tools/.github/actions/report-code-references-to-flagsmith.yml@0.0.1
        with:
          references_json: ${{ steps.find_diff_flag_code_references.outputs.references_json }}
```


## Suggested Plan

Here's an overview of the effort this PoC will take, as action items:


### Backend

1. Ensure there is, or implement an API path to list stale feature flags.
2. Implement a reusable GitHub Action to fetch stale feature flags using that endpoint.
3. Implement a code scanning algorithm that will find feature flag references into a public Docker image.
    - It should accept either a list of feature flags, or some Git diff.
    - It should return code references in JSON format, e.g. `[{file_path, line_number, column_number, code_portion?}, ...]`
4. Implement an API path to receive and persist code references associated to feature flags.
5. Implement a reusable GitHub Action to report code references to the Flagsmith API.
    - This functionality could be bundled to the Docker image, but it might be best to keep steps granular and clear.
6. BONUS: Ship this functionality to customers via [GitHub Actions directory](https://github.com/Flagsmith/flagsmith/actions/new).


### Option 1: UI Changes

1. Display code references in:
    - The list of [stale] feature flags, summarized, e.g. _"3 code references"_ (click to expand).
    - The feature flag modal, detailed, e.g. _"Code references: - foo.py:12, - bar.js:34"_ (click to visit in GitHub).
2. Add the ability to list stale features only.


### Option 2: Recurring Email

1. Send email with N code references grouped by the stale flags they belong to.
    - The CTA should motivate cleaning up.
    - Offer links to GitHub in all code references to maybe encourage cleaning up.


Options 1 and 2 can live together and contribute to each other. We can pick either for a PoC.
