### ISSUE TITLE
Analytics not shown on premise

### ISSUE THREAD

**Issue by JustinBack** [SolidStateGroup/bullet-train-api#526]
InfluxDB is setup according to the docs and working fine, data is downsampled and shown in influx. However analytics for individual flags are not shown in flagsmith

```yml
version: '3.3'
services:

  flagsmith:
    image: 'flagsmith/flagsmith:latest'
    environment:
      - DJANGO_ALLOWED_HOSTS=*
      - DATABASE_URL=*************
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - ENV=prod
      - FLAGSMITH_API_URL=*******
      - ALLOW_ADMIN_INITIATION_VIA_URL=False
      - ENABLE_INFLUXDB_FEATURES=True
      - ENABLE_FLAG_EVALUATION_ANALYTICS=True
      - ALLOW_SIGNUPS=False
      - ALLOW_REGISTRATION_WITHOUT_INVITE=False
      - ENABLE_ADMIN_ACCESS_USER_PASS=True
      - FLAGSMITH_ON_FLAGSMITH_API_KEY=************
      - FLAGSMITH_ON_FLAGSMITH_API_URL=****
      - SENDER_EMAIL=*****
      - EMAIL_HOST=*********
      - EMAIL_HOST_USER=****
      - EMAIL_HOST_PASSWORD=****
      - INFLUXDB_TOKEN=***
      - INFLUXDB_URL=***
      - INFLUXDB_ORG=ae350df1f7371f3c
      - INFLUXDB_BUCKET=flagsmith_api
    networks:
      - net
      - default
networks:
  net:
    external:
      name: traefik-net
```

![grafik](https://user-images.githubusercontent.com/40178814/144244853-28b56b84-97e1-4e22-92e5-e7e1a46e8155.png)

![grafik](https://user-images.githubusercontent.com/40178814/144245034-1d8ea0de-7cfd-4b38-b3fb-d933710ae21e.png)

Running on latest flagsmith with the unified image.
