### ISSUE TITLE
Can't log into Django admin with super user

### ISSUE THREAD

**Issue by jbiffis** [SolidStateGroup/bullet-train-api#594]
I've gone through the steps to create a super user, but whenever I access the django admin page it is prompting me to log in with Google SSO (which isn't connected).  

Can't log in with the super user account

**Comment by dabeeeenster** [comment]
Hi @jbiffis can you provide some background on how you are deploying the platform? Is it a default `docker-compose` setup ? Are you able to provide steps to reproduce from a clean setup?

**Comment by jbiffis** [comment]
Sorry, it is a k8s deployment using Helm charts.  We're not trying to access through the front end but directly hitting the API.  We're getting the login page, but obviously have something misconfigured because it is only prompting for SSO.  Here are the env vars we've set for it.  We're trying to follow these steps https://docs.flagsmith.com/deployment/locally-api#environments-with-no-direct-console-access-eg-heroku-ecs

`api:    
      extraEnv:
        ENV: 'prod'
        PREVENT_SIGNUP: True
        EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'
        EMAIL_HOST: xxxxxx'
        EMAIL_HOST_USER: 'xx@xx.xx'
        EMAIL_HOST_PASSWORD: 'xxxxx'
        INFLUXDB_URL:  'http://xxxxx.svc.cluster.local:8080'
        INFLUXDB_BUCKET: 'flagsmith_api'
        INFLUXDB_ORG: 'xxxxxx'
        INFLUXDB_TOKEN: 'xxxxxx'
        DJANGO_ALLOWED_HOSTS: '*'
        ENABLE_ADMIN_ACCESS_USER_PASS: True`

**Comment by matthewelwell** [comment]
Hi @jbiffis, apologies but I'm not sure I follow still. Could you confirm which page / endpoint you are trying to access please? 

The environment variable `ENABLE_ADMIN_ACCESS_USER_PASS` may be one that could solve your issue? You can find more information about this env var and others that can be configured on the API in our documentation [here](https://docs.flagsmith.com/deployment/locally-api#application-environment-variables).

**Comment by jbiffis** [comment]
Trying to hit :8000/admin/login on the API server (not front end)

Even with that env var set to true we're not seeing it.

**Comment by matthewelwell** [comment]
@jbiffis ok, I think I understand but I am not sure why you wouldn't see the login fields. Some follow up questions I have are: 

 * Can you share any more information on your deployment? Perhaps a larger snippet of your helm chart? 
 * Are you using the flagsmith/flagsmith or the flagsmith/flagsmith-api image?
 * Are you sure that you're setting that environment variable against the correct container (the API container in a dual image set up or the flagsmith container in a single image set up)? 

For reference, I've also included a basic example below of a docker compose setup that gets the API running and shows the email / password option when accessing http://localhost:8000/admin/ in a browser. 

```yml
version: '3'
services: 
  db: 
    image: postgres:11.12-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flagsmith
    container_name: flagsmith_postgres

  api:
    image: flagsmith/flagsmith-api:latest
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgres://postgres:password@db/flagsmith
      DJANGO_ALLOWED_HOSTS: '*'
      DJANGO_SECRET_KEY: some-really-secret-key
      EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
      ENABLE_ADMIN_ACCESS_USER_PASS: True
```
